-- 003_toy_workflow
ALTER TABLE toys ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
CREATE TABLE toy_audit (
  id TEXT PRIMARY KEY,
  toy_id TEXT NOT NULL REFERENCES toys(id) ON DELETE CASCADE,
  actor_id TEXT NOT NULL REFERENCES users(id),
  from_state TEXT NOT NULL,
  to_state TEXT NOT NULL,
  at TEXT NOT NULL
);
