-- 003_tip_workflow
ALTER TABLE tips ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
CREATE TABLE tip_audit (
  id TEXT PRIMARY KEY,
  tip_id TEXT NOT NULL REFERENCES tips(id) ON DELETE CASCADE,
  actor_id TEXT NOT NULL REFERENCES users(id),
  from_state TEXT NOT NULL,
  to_state TEXT NOT NULL,
  at TEXT NOT NULL
);
