"use client";
import { useEffect, useState } from "react";
import { StudioShell } from "@/components/studio-shell"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { api } from "@/lib/client-api";
type Ref={id:string;label?:string};type Result={hybrid:{overall:number};classical:{overall:number};winner:string;gap:number};
export function ComparePage(){const[designs,setDesigns]=useState<Ref[]>([]),[alleles,setAlleles]=useState<Ref[]>([]),[runs,setRuns]=useState<Ref[]>([]),[name,setName]=useState("Peptide prior A/B"),[designId,setDesign]=useState(""),[alleleId,setAllele]=useState(""),[runId,setRun]=useState(""),[result,setResult]=useState<Result|null>(null),[error,setError]=useState("");
useEffect(()=>{void(async()=>{try{const[d,a,r]=await Promise.all([api<{items:Ref[]}>("/api/designs"),api<{items:Ref[]}>("/api/alleles"),api<{items:Ref[]}>("/api/runs")]);setDesigns(d.items);setAlleles(a.items);setRuns(r.items);setDesign(d.items[0]?.id||"");setAllele(a.items[0]?.id||"");setRun(r.items[0]?.id||"")}catch(e){setError(e instanceof Error?e.message:"Could not load comparison references")}})()},[]);
const compare=async(e:React.FormEvent)=>{e.preventDefault();try{setResult((await api<{compare:Result}>("/api/compare",{method:"POST",body:JSON.stringify({name,designId,alleleId,runId})})).compare)}catch(x){setError(x instanceof Error?x.message:"Could not run comparison")}};
const select=(value:string,set:(v:string)=>void,items:Ref[]) => <select className="w-full rounded-md border p-2" value={value} onChange={e=>set(e.target.value)}>{items.map(x=><option key={x.id} value={x.id}>{x.label||x.id.slice(0,8)}</option>)}</select>;
return <StudioShell title="A/B compare" subtitle="Compare hybrid quantum–classical de novo with a classical generative baseline."><form onSubmit={compare} className="grid gap-4 rounded-lg border bg-white p-5 md:grid-cols-2"><div><Label htmlFor="name">Comparison name</Label><Input id="name" value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Design</Label>{select(designId,setDesign,designs)}</div><div><Label>Allele</Label>{select(alleleId,setAllele,alleles)}</div><div><Label>Run</Label>{select(runId,setRun,runs)}</div><Button className="w-fit">Run A/B compare</Button></form>{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}{result&&<section className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-lg border bg-white p-5"><p className="text-sm">Hybrid overall</p><strong className="text-3xl">{result.hybrid.overall}</strong></article><article className="rounded-lg border bg-white p-5"><p className="text-sm">Classical overall</p><strong className="text-3xl">{result.classical.overall}</strong></article><article className="rounded-lg border border-[var(--md-amber)] bg-[var(--studio-warn-soft)] p-5"><p className="text-sm">Winner · gap</p><strong className="text-xl">{result.winner} · {result.gap}</strong></article></section>}</StudioShell>}
export default ComparePage;
