import type { StreamInput, StreamQuality } from "./domain/types";

export type Golden = {
  id: string;
  input: StreamInput;
  expectedRealtime: StreamQuality;
  expectedOfflineBatch: StreamQuality;
};

export const GOLDENS: Golden[] = [
  {
    "id": "sss-001",
    "input": {
      "glossClarity": 0.34,
      "motionStability": 0.39,
      "boundaryConfidence": 0.38,
      "latencyMs": 1085,
      "budgetMs": 600,
      "vocabularyCoverage": 0.28,
      "signerPace": 0.55,
      "occlusionNoise": 0.44,
      "streamJitter": 0.4,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 26.83,
      "latencyScore": 2.8,
      "continuityScore": 46.35,
      "glossaryScore": 16.28,
      "boundaryScore": 11.96,
      "fidelityScore": 15.4,
      "confidence": 14.06,
      "streamContribution": 25.33,
      "batchContribution": 9.48,
      "overall": 19.92
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 29.84,
      "latencyScore": 48.75,
      "continuityScore": 20.45,
      "glossaryScore": 19.45,
      "boundaryScore": 29,
      "fidelityScore": 22.6,
      "confidence": 14.64,
      "streamContribution": 25.15,
      "batchContribution": 19.21,
      "overall": 22.68
    }
  },
  {
    "id": "sss-002",
    "input": {
      "glossClarity": 0.38,
      "motionStability": 0.42,
      "boundaryConfidence": 0.42,
      "latencyMs": 1090.86,
      "budgetMs": 660.69,
      "vocabularyCoverage": 0.32,
      "signerPace": 0.56,
      "occlusionNoise": 0.45,
      "streamJitter": 0.4,
      "segmentBias": "wait_boundary",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 26.4,
      "latencyScore": 2.8,
      "continuityScore": 48.43,
      "glossaryScore": 15.95,
      "boundaryScore": 26.76,
      "fidelityScore": 18.05,
      "confidence": 18.88,
      "streamContribution": 25.88,
      "batchContribution": 10.68,
      "overall": 23.02
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 33.36,
      "latencyScore": 48.75,
      "continuityScore": 22.3,
      "glossaryScore": 22.48,
      "boundaryScore": 31,
      "fidelityScore": 26.04,
      "confidence": 17.48,
      "streamContribution": 27.83,
      "batchContribution": 22.13,
      "overall": 25.71
    }
  },
  {
    "id": "sss-003",
    "input": {
      "glossClarity": 0.42,
      "motionStability": 0.45,
      "boundaryConfidence": 0.4,
      "latencyMs": 1096.72,
      "budgetMs": 601.38,
      "vocabularyCoverage": 0.36,
      "signerPace": 0.51,
      "occlusionNoise": 0.46,
      "streamJitter": 0.36,
      "segmentBias": "batch_only",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 29.46,
      "latencyScore": 0,
      "continuityScore": 51.86,
      "glossaryScore": 19.99,
      "boundaryScore": 13.24,
      "fidelityScore": 20.7,
      "confidence": 16.93,
      "streamContribution": 27.11,
      "batchContribution": 11.88,
      "overall": 21.84
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 35.38,
      "latencyScore": 49.55,
      "continuityScore": 24.15,
      "glossaryScore": 25.51,
      "boundaryScore": 45,
      "fidelityScore": 29.48,
      "confidence": 20.8,
      "streamContribution": 29.77,
      "batchContribution": 25.06,
      "overall": 30.83
    }
  },
  {
    "id": "sss-004",
    "input": {
      "glossClarity": 0.38,
      "motionStability": 0.48,
      "boundaryConfidence": 0.43,
      "latencyMs": 982.59,
      "budgetMs": 662.07,
      "vocabularyCoverage": 0.39,
      "signerPace": 0.51,
      "occlusionNoise": 0.38,
      "streamJitter": 0.37,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 34.61,
      "latencyScore": 3.34,
      "continuityScore": 53.23,
      "glossaryScore": 25.58,
      "boundaryScore": 19.49,
      "fidelityScore": 21.2,
      "confidence": 21.3,
      "streamContribution": 30.39,
      "batchContribution": 11.52,
      "overall": 26.07
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 34.87,
      "latencyScore": 49.35,
      "continuityScore": 24.4,
      "glossaryScore": 27.08,
      "boundaryScore": 31.5,
      "fidelityScore": 29.49,
      "confidence": 21.2,
      "streamContribution": 29.64,
      "batchContribution": 25.07,
      "overall": 28.76
    }
  },
  {
    "id": "sss-005",
    "input": {
      "glossClarity": 0.42,
      "motionStability": 0.44,
      "boundaryConfidence": 0.47,
      "latencyMs": 988.45,
      "budgetMs": 722.76,
      "vocabularyCoverage": 0.35,
      "signerPace": 0.52,
      "occlusionNoise": 0.39,
      "streamJitter": 0.37,
      "segmentBias": "early_flush",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 31.49,
      "latencyScore": 3.34,
      "continuityScore": 52.17,
      "glossaryScore": 19.98,
      "boundaryScore": 23.8,
      "fidelityScore": 21.45,
      "confidence": 20.73,
      "streamContribution": 29,
      "batchContribution": 11.76,
      "overall": 25.1
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 36.95,
      "latencyScore": 49.35,
      "continuityScore": 23.8,
      "glossaryScore": 25.49,
      "boundaryScore": 33.5,
      "fidelityScore": 30,
      "confidence": 21.04,
      "streamContribution": 30.38,
      "batchContribution": 25.5,
      "overall": 29.12
    }
  },
  {
    "id": "sss-006",
    "input": {
      "glossClarity": 0.45,
      "motionStability": 0.47,
      "boundaryConfidence": 0.45,
      "latencyMs": 994.31,
      "budgetMs": 663.45,
      "vocabularyCoverage": 0.39,
      "signerPace": 0.47,
      "occlusionNoise": 0.4,
      "streamJitter": 0.33,
      "segmentBias": "balanced",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 39.12,
      "latencyScore": 4.06,
      "continuityScore": 55.38,
      "glossaryScore": 28.15,
      "boundaryScore": 20.78,
      "fidelityScore": 23.7,
      "confidence": 23.84,
      "streamContribution": 32.85,
      "batchContribution": 12.78,
      "overall": 28.34
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 38.52,
      "latencyScore": 50.15,
      "continuityScore": 25.45,
      "glossaryScore": 28.32,
      "boundaryScore": 32.5,
      "fidelityScore": 32.92,
      "confidence": 23.98,
      "streamContribution": 31.99,
      "batchContribution": 27.98,
      "overall": 31.21
    }
  },
  {
    "id": "sss-007",
    "input": {
      "glossClarity": 0.49,
      "motionStability": 0.5,
      "boundaryConfidence": 0.49,
      "latencyMs": 1000.17,
      "budgetMs": 724.14,
      "vocabularyCoverage": 0.42,
      "signerPace": 0.48,
      "occlusionNoise": 0.41,
      "streamJitter": 0.34,
      "segmentBias": "wait_boundary",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 37.16,
      "latencyScore": 3.88,
      "continuityScore": 57.12,
      "glossaryScore": 26.07,
      "boundaryScore": 35.1,
      "fidelityScore": 26.05,
      "confidence": 27.7,
      "streamContribution": 32.72,
      "batchContribution": 13.86,
      "overall": 30.6
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 41.86,
      "latencyScore": 49.95,
      "continuityScore": 27.3,
      "glossaryScore": 30.78,
      "boundaryScore": 34.5,
      "fidelityScore": 35.99,
      "confidence": 26.44,
      "streamContribution": 34.58,
      "batchContribution": 30.59,
      "overall": 33.9
    }
  },
  {
    "id": "sss-008",
    "input": {
      "glossClarity": 0.45,
      "motionStability": 0.54,
      "boundaryConfidence": 0.53,
      "latencyMs": 886.03,
      "budgetMs": 784.83,
      "vocabularyCoverage": 0.46,
      "signerPace": 0.49,
      "occlusionNoise": 0.34,
      "streamJitter": 0.34,
      "segmentBias": "batch_only",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 38.16,
      "latencyScore": 0,
      "continuityScore": 59.12,
      "glossaryScore": 27.46,
      "boundaryScore": 31.04,
      "fidelityScore": 26.7,
      "confidence": 26.8,
      "streamContribution": 32.43,
      "batchContribution": 13.62,
      "overall": 29.76
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 41.78,
      "latencyScore": 49.95,
      "continuityScore": 27.9,
      "glossaryScore": 32.85,
      "boundaryScore": 51.5,
      "fidelityScore": 36.25,
      "confidence": 27.04,
      "streamContribution": 34.84,
      "batchContribution": 30.81,
      "overall": 37.58
    }
  },
  {
    "id": "sss-009",
    "input": {
      "glossClarity": 0.49,
      "motionStability": 0.57,
      "boundaryConfidence": 0.5,
      "latencyMs": 891.9,
      "budgetMs": 725.52,
      "vocabularyCoverage": 0.5,
      "signerPace": 0.43,
      "occlusionNoise": 0.34,
      "streamJitter": 0.3,
      "segmentBias": "balanced",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 46.89,
      "latencyScore": 4.6,
      "continuityScore": 62.7,
      "glossaryScore": 37.45,
      "boundaryScore": 27.65,
      "fidelityScore": 29.5,
      "confidence": 30.93,
      "streamContribution": 38.06,
      "batchContribution": 14.82,
      "overall": 34.44
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 43.55,
      "latencyScore": 50.75,
      "continuityScore": 29.75,
      "glossaryScore": 35.96,
      "boundaryScore": 35,
      "fidelityScore": 39.82,
      "confidence": 30.54,
      "streamContribution": 36.65,
      "batchContribution": 33.85,
      "overall": 37.29
    }
  },
  {
    "id": "sss-010",
    "input": {
      "glossClarity": 0.53,
      "motionStability": 0.53,
      "boundaryConfidence": 0.54,
      "latencyMs": 897.76,
      "budgetMs": 786.21,
      "vocabularyCoverage": 0.46,
      "signerPace": 0.44,
      "occlusionNoise": 0.35,
      "streamJitter": 0.31,
      "segmentBias": "early_flush",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 42.53,
      "latencyScore": 4.42,
      "continuityScore": 61.31,
      "glossaryScore": 30.61,
      "boundaryScore": 31.61,
      "fidelityScore": 29.75,
      "confidence": 29.64,
      "streamContribution": 36.09,
      "batchContribution": 15.06,
      "overall": 32.82
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 45.63,
      "latencyScore": 50.55,
      "continuityScore": 29.15,
      "glossaryScore": 34.37,
      "boundaryScore": 37,
      "fidelityScore": 40.32,
      "confidence": 30.37,
      "streamContribution": 37.39,
      "batchContribution": 34.27,
      "overall": 37.64
    }
  },
  {
    "id": "sss-011",
    "input": {
      "glossClarity": 0.57,
      "motionStability": 0.56,
      "boundaryConfidence": 0.58,
      "latencyMs": 903.62,
      "budgetMs": 846.9,
      "vocabularyCoverage": 0.49,
      "signerPace": 0.45,
      "occlusionNoise": 0.36,
      "streamJitter": 0.31,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 52.09,
      "latencyScore": 4.42,
      "continuityScore": 63.4,
      "glossaryScore": 38.47,
      "boundaryScore": 35.42,
      "fidelityScore": 32.1,
      "confidence": 34.34,
      "streamContribution": 39.97,
      "batchContribution": 16.14,
      "overall": 37.29
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 48.97,
      "latencyScore": 50.55,
      "continuityScore": 31,
      "glossaryScore": 36.82,
      "boundaryScore": 39,
      "fidelityScore": 43.4,
      "confidence": 32.84,
      "streamContribution": 39.99,
      "batchContribution": 36.89,
      "overall": 40.34
    }
  },
  {
    "id": "sss-012",
    "input": {
      "glossClarity": 0.53,
      "motionStability": 0.59,
      "boundaryConfidence": 0.56,
      "latencyMs": 789.48,
      "budgetMs": 787.59,
      "vocabularyCoverage": 0.53,
      "signerPace": 0.4,
      "occlusionNoise": 0.29,
      "streamJitter": 0.27,
      "segmentBias": "wait_boundary",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 46.3,
      "latencyScore": 5.14,
      "continuityScore": 66.28,
      "glossaryScore": 35.54,
      "boundaryScore": 44.74,
      "fidelityScore": 32.75,
      "confidence": 36.62,
      "streamContribution": 39.24,
      "batchContribution": 15.9,
      "overall": 38.12
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 47.39,
      "latencyScore": 51.35,
      "continuityScore": 31.25,
      "glossaryScore": 38.89,
      "boundaryScore": 38,
      "fidelityScore": 43.65,
      "confidence": 33.91,
      "streamContribution": 39.32,
      "batchContribution": 37.1,
      "overall": 40.72
    }
  },
  {
    "id": "sss-013",
    "input": {
      "glossClarity": 0.57,
      "motionStability": 0.62,
      "boundaryConfidence": 0.6,
      "latencyMs": 795.34,
      "budgetMs": 848.28,
      "vocabularyCoverage": 0.56,
      "signerPace": 0.41,
      "occlusionNoise": 0.3,
      "streamJitter": 0.28,
      "segmentBias": "batch_only",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 49.43,
      "latencyScore": 0,
      "continuityScore": 68.03,
      "glossaryScore": 37.87,
      "boundaryScore": 38.43,
      "fidelityScore": 35.1,
      "confidence": 35.41,
      "streamContribution": 39.15,
      "batchContribution": 16.98,
      "overall": 37.12
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 50.73,
      "latencyScore": 51.15,
      "continuityScore": 33.1,
      "glossaryScore": 41.34,
      "boundaryScore": 55,
      "fidelityScore": 46.72,
      "confidence": 36.37,
      "streamContribution": 41.92,
      "batchContribution": 39.71,
      "overall": 46.11
    }
  },
  {
    "id": "sss-014",
    "input": {
      "glossClarity": 0.61,
      "motionStability": 0.65,
      "boundaryConfidence": 0.63,
      "latencyMs": 801.21,
      "budgetMs": 908.97,
      "vocabularyCoverage": 0.6,
      "signerPace": 0.41,
      "occlusionNoise": 0.3,
      "streamJitter": 0.28,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 59.87,
      "latencyScore": 14.25,
      "continuityScore": 70.27,
      "glossaryScore": 47.77,
      "boundaryScore": 41.29,
      "fidelityScore": 37.9,
      "confidence": 42.17,
      "streamContribution": 48.13,
      "batchContribution": 18.18,
      "overall": 45.27
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 54,
      "latencyScore": 51.15,
      "continuityScore": 34.95,
      "glossaryScore": 44.45,
      "boundaryScore": 41.5,
      "fidelityScore": 50.3,
      "confidence": 39.4,
      "streamContribution": 44.48,
      "batchContribution": 42.76,
      "overall": 46.42
    }
  },
  {
    "id": "sss-015",
    "input": {
      "glossClarity": 0.65,
      "motionStability": 0.61,
      "boundaryConfidence": 0.61,
      "latencyMs": 807.07,
      "budgetMs": 849.66,
      "vocabularyCoverage": 0.56,
      "signerPace": 0.36,
      "occlusionNoise": 0.31,
      "streamJitter": 0.24,
      "segmentBias": "early_flush",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 53.79,
      "latencyScore": 9.61,
      "continuityScore": 70.56,
      "glossaryScore": 41.01,
      "boundaryScore": 39.01,
      "fidelityScore": 38.15,
      "confidence": 39,
      "streamContribution": 44.65,
      "batchContribution": 18.42,
      "overall": 41.46
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 54.58,
      "latencyScore": 51.95,
      "continuityScore": 34.35,
      "glossaryScore": 42.86,
      "boundaryScore": 40.5,
      "fidelityScore": 50.8,
      "confidence": 39.71,
      "streamContribution": 44.47,
      "batchContribution": 43.18,
      "overall": 46.17
    }
  },
  {
    "id": "sss-016",
    "input": {
      "glossClarity": 0.6,
      "motionStability": 0.64,
      "boundaryConfidence": 0.65,
      "latencyMs": 692.93,
      "budgetMs": 910.34,
      "vocabularyCoverage": 0.6,
      "signerPace": 0.37,
      "occlusionNoise": 0.24,
      "streamJitter": 0.24,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 61.06,
      "latencyScore": 24.4,
      "continuityScore": 71.88,
      "glossaryScore": 48.9,
      "boundaryScore": 44.19,
      "fidelityScore": 38.4,
      "confidence": 45.28,
      "streamContribution": 52.45,
      "batchContribution": 18,
      "overall": 48.96
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 54.05,
      "latencyScore": 51.95,
      "continuityScore": 34.4,
      "glossaryScore": 44.73,
      "boundaryScore": 42.5,
      "fidelityScore": 50.53,
      "confidence": 39.93,
      "streamContribution": 44.22,
      "batchContribution": 42.95,
      "overall": 46.82
    }
  },
  {
    "id": "sss-017",
    "input": {
      "glossClarity": 0.64,
      "motionStability": 0.68,
      "boundaryConfidence": 0.69,
      "latencyMs": 698.79,
      "budgetMs": 971.03,
      "vocabularyCoverage": 0.63,
      "signerPace": 0.38,
      "occlusionNoise": 0.25,
      "streamJitter": 0.25,
      "segmentBias": "wait_boundary",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 57.42,
      "latencyScore": 27.48,
      "continuityScore": 74.08,
      "glossaryScore": 44.45,
      "boundaryScore": 57.6,
      "fidelityScore": 40.75,
      "confidence": 48.51,
      "streamContribution": 52.99,
      "batchContribution": 19.08,
      "overall": 51.15
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 57.39,
      "latencyScore": 51.75,
      "continuityScore": 36.6,
      "glossaryScore": 47.18,
      "boundaryScore": 44.5,
      "fidelityScore": 53.6,
      "confidence": 42.39,
      "streamContribution": 47,
      "batchContribution": 45.56,
      "overall": 49.51
    }
  },
  {
    "id": "sss-018",
    "input": {
      "glossClarity": 0.68,
      "motionStability": 0.71,
      "boundaryConfidence": 0.66,
      "latencyMs": 704.66,
      "budgetMs": 911.72,
      "vocabularyCoverage": 0.67,
      "signerPace": 0.32,
      "occlusionNoise": 0.25,
      "streamJitter": 0.21,
      "segmentBias": "batch_only",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 60.61,
      "latencyScore": 12.03,
      "continuityScore": 77.66,
      "glossaryScore": 48.79,
      "boundaryScore": 44.77,
      "fidelityScore": 43.55,
      "confidence": 45.42,
      "streamContribution": 50.1,
      "batchContribution": 20.28,
      "overall": 47.28
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 59.16,
      "latencyScore": 52.55,
      "continuityScore": 38.45,
      "glossaryScore": 50.29,
      "boundaryScore": 58,
      "fidelityScore": 57.17,
      "confidence": 45.89,
      "streamContribution": 48.81,
      "batchContribution": 48.59,
      "overall": 54.61
    }
  },
  {
    "id": "sss-019",
    "input": {
      "glossClarity": 0.72,
      "motionStability": 0.74,
      "boundaryConfidence": 0.7,
      "latencyMs": 710.52,
      "budgetMs": 972.41,
      "vocabularyCoverage": 0.7,
      "signerPace": 0.33,
      "occlusionNoise": 0.26,
      "streamJitter": 0.21,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 71.87,
      "latencyScore": 27.33,
      "continuityScore": 79.75,
      "glossaryScore": 59.03,
      "boundaryScore": 48.19,
      "fidelityScore": 45.9,
      "confidence": 52.58,
      "streamContribution": 59.65,
      "batchContribution": 21.36,
      "overall": 55.97
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 62.5,
      "latencyScore": 52.55,
      "continuityScore": 40.3,
      "glossaryScore": 52.75,
      "boundaryScore": 45,
      "fidelityScore": 60.25,
      "confidence": 48.35,
      "streamContribution": 51.4,
      "batchContribution": 51.21,
      "overall": 54.61
    }
  },
  {
    "id": "sss-020",
    "input": {
      "glossClarity": 0.68,
      "motionStability": 0.7,
      "boundaryConfidence": 0.74,
      "latencyMs": 596.38,
      "budgetMs": 1033.1,
      "vocabularyCoverage": 0.66,
      "signerPace": 0.34,
      "occlusionNoise": 0.19,
      "streamJitter": 0.22,
      "segmentBias": "early_flush",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 62.5,
      "latencyScore": 39.18,
      "continuityScore": 77.82,
      "glossaryScore": 48.49,
      "boundaryScore": 52.94,
      "fidelityScore": 44.15,
      "confidence": 51.16,
      "streamContribution": 59.83,
      "batchContribution": 20.16,
      "overall": 55.5
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 60.98,
      "latencyScore": 52.35,
      "continuityScore": 38.1,
      "glossaryScore": 50.2,
      "boundaryScore": 47,
      "fidelityScore": 57.56,
      "confidence": 45.95,
      "streamContribution": 49.54,
      "batchContribution": 48.93,
      "overall": 52.92
    }
  },
  {
    "id": "sss-021",
    "input": {
      "glossClarity": 0.72,
      "motionStability": 0.73,
      "boundaryConfidence": 0.72,
      "latencyMs": 602.24,
      "budgetMs": 973.79,
      "vocabularyCoverage": 0.7,
      "signerPace": 0.29,
      "occlusionNoise": 0.2,
      "streamJitter": 0.18,
      "segmentBias": "balanced",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 73.68,
      "latencyScore": 36.67,
      "continuityScore": 81.25,
      "glossaryScore": 60.43,
      "boundaryScore": 50.99,
      "fidelityScore": 46.8,
      "confidence": 55.64,
      "streamContribution": 63.87,
      "batchContribution": 21.36,
      "overall": 59.61
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 63,
      "latencyScore": 53.15,
      "continuityScore": 39.95,
      "glossaryScore": 53.23,
      "boundaryScore": 46,
      "fidelityScore": 61.01,
      "confidence": 49.27,
      "streamContribution": 51.48,
      "batchContribution": 51.86,
      "overall": 55.35
    }
  },
  {
    "id": "sss-022",
    "input": {
      "glossClarity": 0.76,
      "motionStability": 0.76,
      "boundaryConfidence": 0.76,
      "latencyMs": 608.1,
      "budgetMs": 1034.48,
      "vocabularyCoverage": 0.73,
      "signerPace": 0.3,
      "occlusionNoise": 0.21,
      "streamJitter": 0.18,
      "segmentBias": "wait_boundary",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 68.68,
      "latencyScore": 39.07,
      "continuityScore": 83.33,
      "glossaryScore": 54.86,
      "boundaryScore": 64.27,
      "fidelityScore": 49.15,
      "confidence": 58.4,
      "streamContribution": 63.69,
      "batchContribution": 22.44,
      "overall": 61.13
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 66.34,
      "latencyScore": 53.15,
      "continuityScore": 41.8,
      "glossaryScore": 55.68,
      "boundaryScore": 48,
      "fidelityScore": 64.08,
      "confidence": 51.73,
      "streamContribution": 54.07,
      "batchContribution": 54.47,
      "overall": 58.04
    }
  },
  {
    "id": "sss-023",
    "input": {
      "glossClarity": 0.8,
      "motionStability": 0.79,
      "boundaryConfidence": 0.79,
      "latencyMs": 613.97,
      "budgetMs": 1095.17,
      "vocabularyCoverage": 0.77,
      "signerPace": 0.3,
      "occlusionNoise": 0.21,
      "streamJitter": 0.19,
      "segmentBias": "batch_only",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 72.23,
      "latencyScore": 29.03,
      "continuityScore": 85.24,
      "glossaryScore": 57.99,
      "boundaryScore": 56.78,
      "fidelityScore": 51.95,
      "confidence": 56.59,
      "streamContribution": 62.17,
      "batchContribution": 23.64,
      "overall": 59.04
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 69.61,
      "latencyScore": 52.95,
      "continuityScore": 43.65,
      "glossaryScore": 58.79,
      "boundaryScore": 64.5,
      "fidelityScore": 67.65,
      "confidence": 54.75,
      "streamContribution": 56.63,
      "batchContribution": 57.5,
      "overall": 63.74
    }
  },
  {
    "id": "sss-024",
    "input": {
      "glossClarity": 0.76,
      "motionStability": 0.83,
      "boundaryConfidence": 0.77,
      "latencyMs": 499.83,
      "budgetMs": 1035.86,
      "vocabularyCoverage": 0.81,
      "signerPace": 0.25,
      "occlusionNoise": 0.14,
      "streamJitter": 0.15,
      "segmentBias": "balanced",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 81.45,
      "latencyScore": 47.87,
      "continuityScore": 88.57,
      "glossaryScore": 69.74,
      "boundaryScore": 56.27,
      "fidelityScore": 52.6,
      "confidence": 63.5,
      "streamContribution": 72.63,
      "batchContribution": 23.4,
      "overall": 67.88
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 68.03,
      "latencyScore": 53.75,
      "continuityScore": 44.25,
      "glossaryScore": 60.86,
      "boundaryScore": 48.5,
      "fidelityScore": 67.9,
      "confidence": 55.82,
      "streamContribution": 56.14,
      "batchContribution": 57.72,
      "overall": 61.42
    }
  },
  {
    "id": "sss-025",
    "input": {
      "glossClarity": 0.8,
      "motionStability": 0.78,
      "boundaryConfidence": 0.81,
      "latencyMs": 505.69,
      "budgetMs": 1096.55,
      "vocabularyCoverage": 0.77,
      "signerPace": 0.26,
      "occlusionNoise": 0.15,
      "streamJitter": 0.15,
      "segmentBias": "early_flush",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 74.04,
      "latencyScore": 49.54,
      "continuityScore": 87.07,
      "glossaryScore": 59.39,
      "boundaryScore": 59.43,
      "fidelityScore": 52.85,
      "confidence": 61.04,
      "streamContribution": 70.22,
      "batchContribution": 23.64,
      "overall": 65.31
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 70.11,
      "latencyScore": 53.75,
      "continuityScore": 43.3,
      "glossaryScore": 59.27,
      "boundaryScore": 50.5,
      "fidelityScore": 68.41,
      "confidence": 55.67,
      "streamContribution": 56.71,
      "batchContribution": 58.15,
      "overall": 61.78
    }
  },
  {
    "id": "sss-026",
    "input": {
      "glossClarity": 0.83,
      "motionStability": 0.82,
      "boundaryConfidence": 0.85,
      "latencyMs": 511.55,
      "budgetMs": 1157.24,
      "vocabularyCoverage": 0.8,
      "signerPace": 0.27,
      "occlusionNoise": 0.16,
      "streamJitter": 0.16,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 86.04,
      "latencyScore": 50.86,
      "continuityScore": 89.04,
      "glossaryScore": 70.48,
      "boundaryScore": 62.58,
      "fidelityScore": 54.8,
      "confidence": 66.63,
      "streamContribution": 75.31,
      "batchContribution": 24.54,
      "overall": 70.97
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 73,
      "latencyScore": 53.55,
      "continuityScore": 45.3,
      "glossaryScore": 61.52,
      "boundaryScore": 52.5,
      "fidelityScore": 70.96,
      "confidence": 57.75,
      "streamContribution": 59.15,
      "batchContribution": 60.32,
      "overall": 64.14
    }
  },
  {
    "id": "sss-027",
    "input": {
      "glossClarity": 0.87,
      "motionStability": 0.85,
      "boundaryConfidence": 0.83,
      "latencyMs": 517.41,
      "budgetMs": 1097.93,
      "vocabularyCoverage": 0.84,
      "signerPace": 0.22,
      "occlusionNoise": 0.17,
      "streamJitter": 0.12,
      "segmentBias": "wait_boundary",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 79.72,
      "latencyScore": 49.29,
      "continuityScore": 92.47,
      "glossaryScore": 65.48,
      "boundaryScore": 70.77,
      "fidelityScore": 57.45,
      "confidence": 67.99,
      "streamContribution": 73.83,
      "batchContribution": 25.74,
      "overall": 70.72
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 75.02,
      "latencyScore": 54.35,
      "continuityScore": 47.15,
      "glossaryScore": 64.55,
      "boundaryScore": 51.5,
      "fidelityScore": 74.4,
      "confidence": 61.06,
      "streamContribution": 61.08,
      "batchContribution": 63.24,
      "overall": 66.56
    }
  },
  {
    "id": "sss-028",
    "input": {
      "glossClarity": 0.83,
      "motionStability": 0.88,
      "boundaryConfidence": 0.86,
      "latencyMs": 403.28,
      "budgetMs": 1158.62,
      "vocabularyCoverage": 0.87,
      "signerPace": 0.22,
      "occlusionNoise": 0.09,
      "streamJitter": 0.12,
      "segmentBias": "batch_only",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 80.58,
      "latencyScore": 46.95,
      "continuityScore": 94.17,
      "glossaryScore": 66.67,
      "boundaryScore": 64.43,
      "fidelityScore": 57.95,
      "confidence": 66.46,
      "streamContribution": 73.9,
      "batchContribution": 25.38,
      "overall": 69.68
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 74.51,
      "latencyScore": 54.35,
      "continuityScore": 47.4,
      "glossaryScore": 66.12,
      "boundaryScore": 68,
      "fidelityScore": 74.41,
      "confidence": 61.46,
      "streamContribution": 60.96,
      "batchContribution": 63.25,
      "overall": 69.89
    }
  },
  {
    "id": "sss-029",
    "input": {
      "glossClarity": 0.87,
      "motionStability": 0.91,
      "boundaryConfidence": 0.9,
      "latencyMs": 409.14,
      "budgetMs": 1219.31,
      "vocabularyCoverage": 0.91,
      "signerPace": 0.23,
      "occlusionNoise": 0.1,
      "streamJitter": 0.13,
      "segmentBias": "balanced",
      "profile": "realtime_stream"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 93.82,
      "latencyScore": 59.75,
      "continuityScore": 95.92,
      "glossaryScore": 79.78,
      "boundaryScore": 67.49,
      "fidelityScore": 60.6,
      "confidence": 74.06,
      "streamContribution": 83.16,
      "batchContribution": 26.58,
      "overall": 78.55
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 78.03,
      "latencyScore": 54.15,
      "continuityScore": 49.25,
      "glossaryScore": 69.15,
      "boundaryScore": 55,
      "fidelityScore": 77.86,
      "confidence": 64.3,
      "streamContribution": 63.64,
      "batchContribution": 66.18,
      "overall": 70.22
    }
  },
  {
    "id": "sss-030",
    "input": {
      "glossClarity": 0.91,
      "motionStability": 0.87,
      "boundaryConfidence": 0.88,
      "latencyMs": 415,
      "budgetMs": 1160,
      "vocabularyCoverage": 0.87,
      "signerPace": 0.18,
      "occlusionNoise": 0.11,
      "streamJitter": 0.09,
      "segmentBias": "early_flush",
      "profile": "offline_batch"
    },
    "expectedRealtime": {
      "mode": "realtime_stream",
      "sentenceScore": 84.8,
      "latencyScore": 58.73,
      "continuityScore": 96.21,
      "glossaryScore": 69.52,
      "boundaryScore": 65.77,
      "fidelityScore": 60.85,
      "confidence": 70.26,
      "streamContribution": 79.91,
      "batchContribution": 26.82,
      "overall": 74.48
    },
    "expectedOfflineBatch": {
      "mode": "offline_batch",
      "sentenceScore": 78.61,
      "latencyScore": 54.95,
      "continuityScore": 48.65,
      "glossaryScore": 67.56,
      "boundaryScore": 54,
      "fidelityScore": 78.36,
      "confidence": 64.62,
      "streamContribution": 63.63,
      "batchContribution": 66.61,
      "overall": 69.97
    }
  }
];
