"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { StudioShell } from "@/components/studio-shell";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { api } from "@/lib/client-api";
type Design={id:string;label:string;recipeNotes:string;lockCondition:string;designChannel:string;status:string};
export function DesignsPage(){const [items,setItems]=useState<Design[]>([]),[label,setLabel]=useState(""),[recipeNotes,setNotes]=useState(""),[lockCondition,setLock]=useState("review"),[designChannel,setChannel]=useState("hybrid_quantum_classical"),[error,setError]=useState("");
const load=async()=>{try{setItems((await api<{items:Design[]}>("/api/designs")).items)}catch(e){setError(e instanceof Error?e.message:"Could not load designs")}};useEffect(()=>{void load()},[]);
const create=async(e:React.FormEvent)=>{e.preventDefault();try{await api("/api/designs",{method:"POST",body:JSON.stringify({label,recipeNotes,lockCondition,designChannel})});setLabel("");setNotes("");await load()}catch(x){setError(x instanceof Error?x.message:"Could not create design")}};
return <StudioShell title="Design recipes" subtitle="Define a de novo design recipe, then create a soft-sim run."><div className="grid gap-8 lg:grid-cols-[20rem_1fr]"><form onSubmit={create} className="space-y-3 rounded-lg border bg-white p-4"><Label htmlFor="design-label">Label</Label><Input id="design-label" value={label} onChange={e=>setLabel(e.target.value)} required/><Label htmlFor="notes">Recipe notes</Label><Input id="notes" value={recipeNotes} onChange={e=>setNotes(e.target.value)} required/><Label htmlFor="lock">Lock condition</Label><Input id="lock" value={lockCondition} onChange={e=>setLock(e.target.value)} required/><Label htmlFor="channel">Design channel</Label><Input id="channel" value={designChannel} onChange={e=>setChannel(e.target.value)} required/><Button>Create recipe</Button></form><section className="space-y-3">{error&&<p className="text-sm text-red-700">{error}</p>}{items.map(d=><article key={d.id} className="rounded-lg border bg-white p-4"><h2 className="font-semibold">{d.label}</h2><p className="text-sm text-slate-600">{d.designChannel} · {d.lockCondition} · {d.status}</p><p className="mt-2 text-sm">{d.recipeNotes}</p></article>)}<Button asChild variant="outline"><Link href="/runs">Configure a run</Link></Button></section></div></StudioShell>}
export default DesignsPage;
