-- 003_fob_workflow
ALTER TABLE fobs ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
CREATE TABLE fob_audit (
  id TEXT PRIMARY KEY,
  fob_id TEXT NOT NULL REFERENCES fobs(id) ON DELETE CASCADE,
  actor_id TEXT NOT NULL REFERENCES users(id),
  from_state TEXT NOT NULL,
  to_state TEXT NOT NULL,
  at TEXT NOT NULL
);
